# Generated by Django 2.2.2 on 2019-06-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0002_auto_20190608_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
